services:
  mc-server:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    restart: always
    ports:
      - "25565:25565"
    mem_limit: 3g
    cpus: 2
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "LATEST"
      MEMORY: "2G"
      MOTD: "server mc homelab"
      MAX_PLAYERS: 15
      DIFFICULTY: "normal"
      VIEW_DISTANCE: 10
    volumes:
      - ./Minecraft/data:/data

  terraria-server:
    image: jacobsmile/tmodloader1.4:latest
    container_name: terraria-server
    restart: always
    ports:
      - "7777:7777"
    mem_limit: 2g
    cpus: 2
    stdin_open: true
    tty: true
    environment:
      TMOD_WORLDNAME: "${TERRARIA_WORLD_NAME}"
      TMOD_WORLDSIZE: "${TERRARIA_WORLD_SIZE}"
      TMOD_WORLDSEED: "${TERRARIA_SEED}"
      TMOD_DIFFICULTY: "${TERRARIA_DIFFICULTY}"
      TMOD_MAXPLAYERS: "${TERRARIA_MAX_PLAYERS}"
      TMOD_PASS: "${TERRARIA_PASSWORD}"
      TMOD_MOTD: "${TERRARIA_MOTD}"
    volumes:
      - ./tModLoader:/data
