services:
  mc-server:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    restart: always
    ports:
      - "25565:25565"
    mem_limit: 3g
    cpus: 2
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "LATEST"
      MEMORY: "2G"
      MOTD: "server mc homelab"
      MAX_PLAYERS: 15
      DIFFICULTY: "normal"
      VIEW_DISTANCE: 10
    volumes:
      - ./Minecraft/data:/data

  terraria-server:
    image: jacobalberty/tmodloader:latest
    container_name: terraria-server
    restart: always
    ports:
      - "7777:7777"
    mem_limit: 2g
    cpus: 2
    stdin_open: true
    tty: true
    environment:
      world: "${TERRARIA_WORLD_NAME}.wld"
      autocreate: ${TERRARIA_WORLD_SIZE}
      seed: ${TERRARIA_SEED}
      difficulty: ${TERRARIA_DIFFICULTY}
      maxplayers: ${TERRARIA_MAX_PLAYERS}
      password: ${TERARRIA_PASSWORD}
      motd: ${TERRARIA_MOTD}
    volumes:
      - ./tModLoader/Worlds:/home/tml/.local/share/Terraria/tModLoader/Worlds
      - ./tModLoader/Mods:/home/tml/.local/share/Terraria/tModLoader/Mods
